export const NEO_MINT = {
  textTitle: 'var(--text-title)',
  primary: 'var(--primary)',
  primaryHover: 'var(--primary-hover)',
  surface: 'var(--surface)',
  surfaceRaised: 'var(--surface-raised)',
  surfaceSoft: 'var(--surface-soft)',
  surfaceMuted: 'var(--surface-muted)',
  surfaceInset: 'var(--surface-inset)',
  textBody: 'var(--text-body)',
  textMuted: 'var(--text-muted)',
  cardBorderSoft: 'var(--card-border-soft)',
  borderStrong: 'var(--border-strong)',
  outline: 'var(--surface-muted)',
  textBlack: 'var(--text-title)',
  danger: 'var(--danger)',
  dangerBorder: 'var(--danger-border)',
  dangerSoft: 'var(--danger-bg)',
  success: 'var(--success)',
  successSoft: 'var(--success-bg)',
  successBorder: 'var(--success-border)',
  dueDateChange: 'var(--due-date-change)',
  dueDateChangeSoft: 'var(--due-date-change-bg)',
  shadowSm: 'var(--shadow-sm)',
  shadowMd: 'var(--shadow-md)',
  shadowLg: 'var(--shadow-lg)',
} as const;
