begin;

create table if not exists public.recurrent_subtask_occurrences (
  id uuid primary key default gen_random_uuid(),
  recurrent_subtask_id uuid not null references public.recurrent_subtasks(id) on delete cascade,
  notebook_id uuid not null references public.notebooks(id) on delete cascade,
  space_id uuid not null references public.spaces(id) on delete cascade,
  occurrence_date date not null,
  status text not null,
  work_hours numeric(4, 1) not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint recurrent_subtask_occurrences_unique unique (recurrent_subtask_id, occurrence_date),
  constraint recurrent_subtask_occurrences_status_valid
    check (status in ('IN PROGRESS', 'DONE')),
  constraint recurrent_subtask_occurrences_work_hours_valid
    check (work_hours in (0, 0.5, 1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)),
  constraint recurrent_subtask_occurrences_completion_valid
    check (
      (status = 'IN PROGRESS' and completed_at is null and work_hours = 0)
      or (status = 'DONE' and completed_at is not null)
    )
);

create table if not exists public.recurrent_subtask_work_events (
  id bigint generated by default as identity primary key,
  occurrence_id uuid not null references public.recurrent_subtask_occurrences(id) on delete cascade,
  recurrent_subtask_id uuid not null references public.recurrent_subtasks(id) on delete cascade,
  notebook_id uuid not null references public.notebooks(id) on delete cascade,
  space_id uuid not null references public.spaces(id) on delete cascade,
  occurrence_date date not null,
  status text not null,
  work_hours numeric(4, 1) not null default 0,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  constraint recurrent_subtask_work_events_status_valid
    check (status in ('IN PROGRESS', 'DONE')),
  constraint recurrent_subtask_work_events_work_hours_valid
    check (work_hours in (0, 0.5, 1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24))
);

create index if not exists recurrent_subtask_occurrences_notebook_date_idx
  on public.recurrent_subtask_occurrences (notebook_id, occurrence_date, recurrent_subtask_id);
create index if not exists recurrent_subtask_occurrences_space_date_idx
  on public.recurrent_subtask_occurrences (space_id, occurrence_date);
create index if not exists recurrent_subtask_work_events_notebook_changed_idx
  on public.recurrent_subtask_work_events (notebook_id, changed_at desc, id desc);
create index if not exists recurrent_subtask_work_events_subtask_date_idx
  on public.recurrent_subtask_work_events (recurrent_subtask_id, occurrence_date, changed_at desc);

alter table public.recurrent_subtask_occurrences enable row level security;
alter table public.recurrent_subtask_work_events enable row level security;

create policy recurrent_subtask_occurrences_select_members
  on public.recurrent_subtask_occurrences
  for select
  to authenticated
  using (private.can_access_notebook(notebook_id));

create policy recurrent_subtask_work_events_select_members
  on public.recurrent_subtask_work_events
  for select
  to authenticated
  using (private.can_access_notebook(notebook_id));

revoke all on public.recurrent_subtask_occurrences from public, anon;
revoke all on public.recurrent_subtask_work_events from public, anon;
grant select on public.recurrent_subtask_occurrences to authenticated;
grant select on public.recurrent_subtask_work_events to authenticated;

create or replace function private.recurrent_subtask_occurs_on_date(
  requested_recurrence public.recurrence_type,
  requested_anchor_date date,
  requested_weekdays smallint[],
  requested_occurrence_date date
)
returns boolean
language plpgsql
stable
set search_path = ''
as $$
declare
  month_interval integer;
  months_apart integer;
  expected_day integer;
begin
  if requested_occurrence_date < requested_anchor_date then
    return false;
  end if;

  if requested_recurrence in ('weekly', 'bi-weekly') then
    if not (extract(isodow from requested_occurrence_date)::smallint = any(requested_weekdays)) then
      return false;
    end if;
    if requested_recurrence = 'weekly' then
      return true;
    end if;
    return mod(
      ((date_trunc('week', requested_occurrence_date)::date
        - date_trunc('week', requested_anchor_date)::date) / 7),
      2
    ) = 0;
  end if;

  month_interval := case requested_recurrence
    when 'monthly' then 1
    when 'quarterly' then 3
    when 'half-yearly' then 6
    when 'yearly' then 12
  end;
  months_apart :=
    (extract(year from requested_occurrence_date)::integer
      - extract(year from requested_anchor_date)::integer) * 12
    + extract(month from requested_occurrence_date)::integer
    - extract(month from requested_anchor_date)::integer;
  if months_apart < 0 or mod(months_apart, month_interval) <> 0 then
    return false;
  end if;

  expected_day := least(
    extract(day from requested_anchor_date)::integer,
    extract(
      day from (
        date_trunc('month', requested_occurrence_date)
        + interval '1 month'
        - interval '1 day'
      )
    )::integer
  );
  return extract(day from requested_occurrence_date)::integer = expected_day;
end;
$$;

create or replace function public.cycle_recurrent_subtask_occurrence(
  requested_notebook_id uuid,
  requested_subtask_id uuid,
  requested_occurrence_date date,
  requested_work_hours numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_local_date date := (clock_timestamp() at time zone 'Asia/Ho_Chi_Minh')::date;
  parent_space_id uuid;
  stored_recurrence public.recurrence_type;
  stored_anchor_date date;
  stored_weekdays smallint[];
  occurrence_record public.recurrent_subtask_occurrences%rowtype;
begin
  if not private.has_notebook_permission(requested_notebook_id, 'manage_tasks') then
    raise exception 'Not authorized to log recurrent work' using errcode = '42501';
  end if;
  if requested_occurrence_date is null
    or requested_occurrence_date not between current_local_date - 1 and current_local_date
  then
    raise exception 'Recurrent work can only be logged for today or yesterday' using errcode = '22023';
  end if;
  if requested_work_hours is not null
    and requested_work_hours not in (0, 0.5, 1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)
  then
    raise exception 'Invalid recurrent work hours' using errcode = '22023';
  end if;

  select
    task.space_id,
    subtask.recurrence,
    subtask.anchor_date,
    subtask.weekdays
  into
    parent_space_id,
    stored_recurrence,
    stored_anchor_date,
    stored_weekdays
  from public.recurrent_subtasks subtask
  join public.recurrent_tasks task on task.id = subtask.recurrent_task_id
  where subtask.id = requested_subtask_id
    and task.notebook_id = requested_notebook_id;

  if parent_space_id is null then
    raise exception 'Recurrent subtask was not found in this notebook' using errcode = 'P0002';
  end if;
  if not private.recurrent_subtask_occurs_on_date(
    stored_recurrence,
    stored_anchor_date,
    stored_weekdays,
    requested_occurrence_date
  ) then
    raise exception 'The selected date is not a recurrent occurrence' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      requested_subtask_id::text || ':' || requested_occurrence_date::text,
      17022026
    )
  );

  select occurrence.*
  into occurrence_record
  from public.recurrent_subtask_occurrences occurrence
  where occurrence.recurrent_subtask_id = requested_subtask_id
    and occurrence.occurrence_date = requested_occurrence_date
  for update;

  if occurrence_record.id is null then
    if requested_work_hours is not null then
      raise exception 'Start recurrent work before completing it' using errcode = '22023';
    end if;

    insert into public.recurrent_subtask_occurrences (
      recurrent_subtask_id,
      notebook_id,
      space_id,
      occurrence_date,
      status
    ) values (
      requested_subtask_id,
      requested_notebook_id,
      parent_space_id,
      requested_occurrence_date,
      'IN PROGRESS'
    )
    returning * into occurrence_record;

    insert into public.recurrent_subtask_work_events (
      occurrence_id,
      recurrent_subtask_id,
      notebook_id,
      space_id,
      occurrence_date,
      status,
      changed_by
    ) values (
      occurrence_record.id,
      requested_subtask_id,
      requested_notebook_id,
      parent_space_id,
      requested_occurrence_date,
      'IN PROGRESS',
      auth.uid()
    );

    return jsonb_build_object('status', 'IN PROGRESS', 'workHours', 0);
  end if;

  if occurrence_record.status = 'IN PROGRESS' then
    if requested_work_hours is null then
      raise exception 'Work hours are required to complete recurrent work' using errcode = '22023';
    end if;

    update public.recurrent_subtask_occurrences occurrence
    set status = 'DONE',
        work_hours = requested_work_hours,
        completed_at = now(),
        updated_at = now()
    where occurrence.id = occurrence_record.id;

    insert into public.recurrent_subtask_work_events (
      occurrence_id,
      recurrent_subtask_id,
      notebook_id,
      space_id,
      occurrence_date,
      status,
      work_hours,
      changed_by
    ) values (
      occurrence_record.id,
      requested_subtask_id,
      requested_notebook_id,
      parent_space_id,
      requested_occurrence_date,
      'DONE',
      requested_work_hours,
      auth.uid()
    );

    return jsonb_build_object('status', 'DONE', 'workHours', requested_work_hours);
  end if;

  delete from public.recurrent_subtask_occurrences occurrence
  where occurrence.id = occurrence_record.id;

  return jsonb_build_object('status', 'TO DO', 'workHours', 0);
end;
$$;

revoke all on function public.cycle_recurrent_subtask_occurrence(uuid, uuid, date, numeric)
  from public, anon;
grant execute on function public.cycle_recurrent_subtask_occurrence(uuid, uuid, date, numeric)
  to authenticated;

create or replace function private.prune_notebook_logs(requested_notebook_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.acquire_quota_lock('notebook:logs:' || requested_notebook_id::text);

  with excess_logs as (
    select log_type, log_id
    from (
      select 'status'::text as log_type, event.id as log_id, event.changed_at
      from public.task_status_events event
      where event.notebook_id = requested_notebook_id
      union all
      select 'due_date'::text as log_type, event.id as log_id, event.changed_at
      from public.task_due_date_events event
      where event.notebook_id = requested_notebook_id
      union all
      select 'subtask_completion'::text as log_type, event.id as log_id, event.changed_at
      from public.subtask_completion_events event
      where event.notebook_id = requested_notebook_id
      union all
      select 'recurrent_work'::text as log_type, event.id as log_id, event.changed_at
      from public.recurrent_subtask_work_events event
      where event.notebook_id = requested_notebook_id
    ) log_entry
    order by changed_at desc, log_id desc
    offset 2000
  ), deleted_status as (
    delete from public.task_status_events event
    using excess_logs excess
    where excess.log_type = 'status' and event.id = excess.log_id
  ), deleted_due_dates as (
    delete from public.task_due_date_events event
    using excess_logs excess
    where excess.log_type = 'due_date' and event.id = excess.log_id
  ), deleted_subtask_completion as (
    delete from public.subtask_completion_events event
    using excess_logs excess
    where excess.log_type = 'subtask_completion' and event.id = excess.log_id
  )
  delete from public.recurrent_subtask_work_events event
  using excess_logs excess
  where excess.log_type = 'recurrent_work' and event.id = excess.log_id;
end;
$$;

drop trigger if exists recurrent_subtask_work_events_prune_notebook_logs
  on public.recurrent_subtask_work_events;
create trigger recurrent_subtask_work_events_prune_notebook_logs
  after insert on public.recurrent_subtask_work_events
  for each row execute function private.prune_notebook_logs_after_insert();

commit;
